version: '3'
services:
  redis:
    image: redis:alpine

  app01:
    build: .
    environment:
      - REDIS_ENDPOINT=redis
    depends_on:
      - redis
  
  app02:
    build: .
    environment:
      - REDIS_ENDPOINT=redis
    depends_on:
      - redis
  
  app03:
    build: .
    environment:
      - REDIS_ENDPOINT=redis
    depends_on:
      - redis

  web:
    build: nginx/
    ports:
      - 80:80
    depends_on:
      - app01
      - app02
      - app03
